<a href="https://colab.research.google.com/github/Divyagowribabu/Data_Engineering-Assignment/blob/main/googlecolab/problem_1_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEM 1: Employee Productivity Prediction
(Multivariate Linear Regression)

Problem Statement:
A company wants to predict employee productivity scores to improve workforce planning and training programs. You are hired as a Data Scientist to build a multivariate linear regression model that predicts an employee’s Productivity Score based on multiple work-related factors.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/employee_productivity.csv')
df

   Experience  TrainingHours  WorkingHours  Projects  ProductivityScore
0           2             40            38         3                 62
1           5             60            42         6                 78
2           1             20            35         2                 55
3           8             80            45         8                 88
4           4             50            40         5                 72
5          10             90            48         9                 92
6           3             30            37         4                 65
7           6             70            44         7                 82
8           7             75            46         7                 85
9           2             25            36         3                 60

In [ ]:
X = df[['Experience', 'TrainingHours', 'WorkingHours', 'Projects']]
y = df['ProductivityScore']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})
coefficients

         Feature  Coefficient
0     Experience    -0.263658
1  TrainingHours     0.272684
2   WorkingHours    -1.085511
3       Projects     4.885986